### ISSUE TITLE
exception on circle E-Mail share

### ISSUE THREAD

**Issue by Superjamp** [nextcloud/files_downloadlimit#121]
Error: OCA\Files_DownloadLimit\Db\LimitMapper::get(): Argument #1 ($token) must be of type string, null given, called in /var/www/html/nextcloud/apps/files_downloadlimit/lib/Listener/BeforeTemplateRenderedListener.php on line 57 in file '/var/www/html/nextcloud/apps/files_downloadlimit/lib/Db/LimitMapper.php' line 36

**Comment by skjnldsv** [comment]
Hi,

We do not support circle email share :thinking: 
Did you change anything to this app? Are you usign the appstore version?

**Comment by Superjamp** [comment]
stock app's from appstore

nc 23.0.7
circles 23.1.2
downloadlimit 1.0.1

I have not checked exactly why the return is null.
The token is listed in oc_circles_token

**Comment by skjnldsv** [comment]
cc @ArtificialOwl , are you using `SHARE_TYPE_EMAIL` for circles?
Do you know why is there no token bound to it? :)
