### ISSUE TITLE
l10n: Singular and plural

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/files_downloadlimit#86]
@skjnldsv For the following text string, add singular and plural for `{limit}` and `{countLeft}`.

https://github.com/nextcloud/files_downloadlimit/blob/0f2b6d5d0c66f2b6cf5398ee566acf50248b2104/src/models/DownloadLimitAction.js#L69

You should also think about separating sentences, because there may be different situations in which the limit of downloads for the remaining downloads to be downloaded may be different.

**Comment by skjnldsv** [comment]
> You should also think about separating sentences, because there may be different situations in which the limit of downloads for the remaining downloads to be downloaded may be different.

Could you clarify? :)
Not sure I get it

**Comment by Valdnet** [comment]
> Could you clarify? :)

For downloads greater than or equal to 5:
This share was limited to 10 downloads. There is still **4** left allowed.
This share was limited to 5 downloads. There is still **4** left allowed.
This share was limited to 5 downloads. There is still **2** left allowed.
This share was limited to 5 downloads. There is still **1** left allowed.

For downloads from 2 to 4:
This share was limited to 2 downloads. There is still **1** left allowed.
This share was limited to 3 downloads. There is still **2** left allowed.
This share was limited to 3 downloads. There is still **1** left allowed.
This share was limited to 4 downloads. There is still **3** left allowed.

If the text string appears up to the 1 download limit then also:
This share was limited to 1 download. There is still **1** left allowed.

Note that there may be a text string with a limit of e.g. 10 downloads, where e.g. 5 more are available, but there may e.g. be 2 more downloads available.
Therefore, the text string must be split into two text strings:
`This share was limited to {limit} downloads.`
`There is still {countLeft} left allowed.`
This is the only way to match the appropriate singular or plural for the variable `{limit}` and and separately for the variable `{countLeft}`.

**Comment by susnux** [comment]
Fixed with the Typescript rewrite
